steps:
  - name: demographics_visits
    left_dataset: demographics
    right_dataset: visits
    how: left
    "on": [patient_id]
    expected_relationship: one_to_many
  - name: patient_visits_labs
    left_dataset: demographics_visits
    right_dataset: labs
    how: left
    "on": [patient_id, visit_date]
    expected_relationship: one_to_one_or_many
  - name: patient_visits_labs_outcomes
    left_dataset: patient_visits_labs
    right_dataset: outcomes
    how: left
    "on": [patient_id]
    expected_relationship: one_to_one
