rules:
- name: severe_disease_allowed
  type: in_set
  column: severe_disease
  values:
  - Y
  - N
- name: event_before_followup
  type: compare_dates
  left: last_followup_date
  operator: '>='
  right: event_date
  allow_na: true
